name: treac
version: 0.1
summary: TREAC - The Treadmill Controller
description: Provides an API for controlling a treadmill on a Raspberry Pi
confinement: devmode # needs i2c interface
grade: devel

apps:
  treacd:
    command: bin/treac --port 8000 0.0.0.0
    daemon: simple
    plugs: [network-bind]
#  servod:
#    command: usr/bin/servod
#    daemon: forking
#    uses: [listener]

parts:
    treac:
        plugin: python
        source: .
        build-packages: [gcc]
#    servoblaster:
#        plugin: make
#        source: git://github.com/richardghirst/PiBits.git
#        directory: ServoBlaster/user
#    servoblaster-install:
#        plugin: copy
#        files:
#            parts/servoblaster/build/ServoBlaster/user/servod: usr/bin/servod
