name: treac
version: 0.1
summary: TREAC - The Treadmill Controller
description: Provides an API for controlling a treadmill on a Raspberry Pi
confinement: devmode # needs i2c interface
grade: devel

apps:
  treacd:
    command: bin/treac --port 8000 0.0.0.0
    daemon: simple
    plugs: [network-bind]
  servod:
    command: ServoBlaster/user/servod
#    daemon: forking

parts:
    treac:
        plugin: python
        source: .
        build-packages: [gcc]
    servoblaster:
        plugin: make
        source: git://github.com/richardghirst/PiBits.git
        artifacts: [ServoBlaster/user/servod]
        make-parameters: [-C, ServoBlaster/user]
        build-packages: [gcc, libc6-dev]
